Mentor.create([
  { name: "Alex Johnson", occupation: "Software Engineer", about: "Experienced in web development and software design.", hourly_fee: 50.0, year_of_experience: 5, location: "New York, USA", skills: "Ruby on Rails, JavaScript", photo_url: "https://res.cloudinary.com/dc2w0r9kz/image/upload/v1707287652/ozqwi3l32ohljjihqvnq.png" },
  { name: "Patricia Smith", occupation: "Data Scientist", about: "Specialist in data analytics and machine learning.", hourly_fee: 70.0, year_of_experience: 8, location: "San Francisco, USA", skills: "Python, Machine Learning", photo_url: "https://res.cloudinary.com/dc2w0r9kz/image/upload/v1707287655/sbwgrb7xjyc2yfmlqhza.png" },
  { name: "Raj Patel", occupation: "UX/UI Designer", about: "Passionate about creating user-friendly designs.", hourly_fee: 60.0, year_of_experience: 4, location: "London, UK", skills: "Figma, Sketch", photo_url: "https://res.cloudinary.com/dc2w0r9kz/image/upload/v1707287654/dlagd7ihcfltpaxyyyrk.png" },
  { name: "Liu Wei", occupation: "Project Manager", about: "Expert in agile methodologies and team management.", hourly_fee: 55.0, year_of_experience: 6, location: "Beijing, China", skills: "Agile, Scrum", photo_url: "https://res.cloudinary.com/dc2w0r9kz/image/upload/v1707287653/tenye3epuq4ubb0ixmbr.png" },
  { name: "Marie Curie", occupation: "Research Scientist", about: "Focused on renewable energy research.", hourly_fee: 80.0, year_of_experience: 10, location: "Paris, France", skills: "Renewable Energy, Research", photo_url: "https://res.cloudinary.com/dc2w0r9kz/image/upload/v1707287653/tfc7k1ztw0d1rgtoximm.png" },
  { name: "Carlos Hernandez", occupation: "Marketing Specialist", about: "Expert in digital marketing and SEO.", hourly_fee: 45.0, year_of_experience: 3, location: "Madrid, Spain", skills: "SEO, Digital Marketing", photo_url: "https://res.cloudinary.com/dc2w0r9kz/image/upload/v1707287653/pidr8vcrhivltdwutlnr.png" },
  { name: "Amina Mohammed", occupation: "Civil Engineer", about: "Skilled in urban planning and sustainable design.", hourly_fee: 65.0, year_of_experience: 7, location: "Lagos, Nigeria", skills: "Urban Planning, Sustainable Design", photo_url: "https://res.cloudinary.com/dc2w0r9kz/image/upload/v1707287653/da3pv2qvxm0ascwrbjoq.png" },
  { name: "Elena Petrova", occupation: "Financial Analyst", about: "Specializing in investment strategies and market analysis.", hourly_fee: 75.0, year_of_experience: 9, location: "Moscow, Russia", skills: "Investment Strategies, Market Analysis", photo_url: "https://res.cloudinary.com/dc2w0r9kz/image/upload/v1707287653/blu2yb9wkifh5kdeswsx.png" },
  { name: "Michael Brown", occupation: "Graphic Designer", about: "Creative designer focused on branding and visual identities.", hourly_fee: 50.0, year_of_experience: 5, location: "Sydney, Australia", skills: "Branding, Adobe Creative Suite", photo_url: "https://res.cloudinary.com/dc2w0r9kz/image/upload/v1707287654/nxjdbqzaayops2fssm1u.png" },
  { name: "Sara Al-Maktoum", occupation: "IT Consultant", about: "Providing solutions for cloud computing and IT infrastructure.", hourly_fee: 65.0, year_of_experience: 6, location: "Dubai, UAE", skills: "Cloud Computing, IT Infrastructure", photo_url: "https://res.cloudinary.com/dc2w0r9kz/image/upload/v1707287655/avfvf9pcl9vvxwkhc1hp.png" }
])

puts "Seeded 10 mentors successfully."
