Mentor.create([
  { name: "Alex Johnson", occupation: "Software Engineer", about: "Experienced in web development and software design.", hourly_fee: 50.0, year_of_experience: 5, location: "New York, USA", skills: "Ruby on Rails, JavaScript", photo_url: "https://drive.google.com/file/d/1Bres5ZFonl9LXDSAbdFW0XMGzf1iVPP4/view?usp=drive_link" },
  { name: "Patricia Smith", occupation: "Data Scientist", about: "Specialist in data analytics and machine learning.", hourly_fee: 70.0, year_of_experience: 8, location: "San Francisco, USA", skills: "Python, Machine Learning", photo_url: "https://drive.google.com/file/d/1uOO78XwgxCKHZdyCPa_WccNPxu785VNw/view?usp=drive_link" },
  { name: "Raj Patel", occupation: "UX/UI Designer", about: "Passionate about creating user-friendly designs.", hourly_fee: 60.0, year_of_experience: 4, location: "London, UK", skills: "Figma, Sketch", photo_url: "https://drive.google.com/file/d/1C9TwhFK7ZYK18Gb5FgLzx1c2q_kiklaP/view?usp=drive_link" },
  { name: "Liu Wei", occupation: "Project Manager", about: "Expert in agile methodologies and team management.", hourly_fee: 55.0, year_of_experience: 6, location: "Beijing, China", skills: "Agile, Scrum", photo_url: "https://drive.google.com/file/d/1fBT5KX0K6HUepo_X3sZ7xEShTKfeXa9x/view?usp=drive_link" },
  { name: "Marie Curie", occupation: "Research Scientist", about: "Focused on renewable energy research.", hourly_fee: 80.0, year_of_experience: 10, location: "Paris, France", skills: "Renewable Energy, Research", photo_url: "https://drive.google.com/file/d/1DpePywrqD9-KHOP6e2CKF-_fShjULGiO/view?usp=drive_link" },
  { name: "Carlos Hernandez", occupation: "Marketing Specialist", about: "Expert in digital marketing and SEO.", hourly_fee: 45.0, year_of_experience: 3, location: "Madrid, Spain", skills: "SEO, Digital Marketing", photo_url: "https://drive.google.com/file/d/1bGDkFHO_Fy3pzQBh3i7iKuc6v0ZqqnxZ/view?usp=drive_link" },
  { name: "Amina Mohammed", occupation: "Civil Engineer", about: "Skilled in urban planning and sustainable design.", hourly_fee: 65.0, year_of_experience: 7, location: "Lagos, Nigeria", skills: "Urban Planning, Sustainable Design", photo_url: "https://drive.google.com/file/d/1TtsS9YOD3Vg1AYCnQaBaj1rzI55j_JfD/view?usp=drive_link" },
  { name: "Elena Petrova", occupation: "Financial Analyst", about: "Specializing in investment strategies and market analysis.", hourly_fee: 75.0, year_of_experience: 9, location: "Moscow, Russia", skills: "Investment Strategies, Market Analysis", photo_url: "https://drive.google.com/file/d/1bC7RVrDWhDp6N_OUfskuDLQ_on_Yh4u8/view?usp=drive_link" },
  { name: "Michael Brown", occupation: "Graphic Designer", about: "Creative designer focused on branding and visual identities.", hourly_fee: 50.0, year_of_experience: 5, location: "Sydney, Australia", skills: "Branding, Adobe Creative Suite", photo_url: "https://drive.google.com/file/d/13AoQmUd0yD1hqtqTJuBwJIIFDod4ZP0N/view?usp=drive_link" },
  { name: "Sara Al-Maktoum", occupation: "IT Consultant", about: "Providing solutions for cloud computing and IT infrastructure.", hourly_fee: 65.0, year_of_experience: 6, location: "Dubai, UAE", skills: "Cloud Computing, IT Infrastructure", photo_url: "https://drive.google.com/file/d/12tGephuCC47ntUL5LK1d0sqdr9WEOT8G/view?usp=drive_link" }
])

puts "Seeded 10 mentors successfully."